#!/usr/bin/env bash

set -eu

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null && pwd )"

sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"

cd ~
git clone https://github.com/svetlyak40wt/dotfiler .dotfiler

( find "$DIR" -mindepth 1 -maxdepth 1 -type d | grep -Ev "^local_" && "$DIR/local_$HOST" ) \
| while read f; do
    fname="$(basename "$f")"
    ln -s "$DIR/$fname" ~/.dotfiles/$fname
done

.dotfiler/bin/dot update
